const express = require("express");
const router = express.Router();
const bcrypt = require("bcryptjs");
const jw = require("jsonwebtoken");
const UsuarioController = require("../Controllers/UsuarioController");

router.get("/admin", UsuarioController.adminRoute);
router.get("/cliente", UsuarioController.clienteRoute);
router.put("/actualizaRol/:id", UsuarioController.actualizaRolUsuario);
router.put("/actualiza/:id", UsuarioController.actualizaDatos);
router.delete("/deleteCliente/:id", UsuarioController.eliminarCliente);
router.get("/getDetalles/:id", UsuarioController.obtenerUsuarioById);
router.put("/actualizaxCorreo", UsuarioController.actualizarPasswordxCorreo);
router.put("/actualizaxPregunta",UsuarioController.actualizarPasswordxPregunta);
router.post("/token", UsuarioController.BuscaUsuarioByToken);
router.get("/buscaUsuarioByCorreo/:correo",UsuarioController.buscaUsuarioByCorreo);
router.post("/correo", UsuarioController.BuscaUsuarioByCorreo);
router.get("/miPerfil/:correo", UsuarioController.perfilUsuario);
router.get("/getUsuarios", UsuarioController.obtenerUsuarios);
router.post("/respuesta", UsuarioController.BuscaUsuarioByPreguntayRespuesta);
router.post("/signUp", UsuarioController.crearUsuario);
router.post("/signIn", UsuarioController.Login);
router.get("/", UsuarioController.obtenerUsuarios);
module.exports = router;
